### ISSUE TITLE
Nothing to publish

### ISSUE THREAD

**Issue by kenske** [spekkionu/laravel-zend-acl#7]
When trying to publish the config, I'm getting the following:

``
$ php artisan vendor:publish --provider=Spekkionu\ZendAcl\ZendAclServiceProvider
Nothing to publish for tag []
``
I checked both the config and http directories and no files are being created.

I'm using Laravel 5.2.15.

**Comment by spekkionu** [comment]
Try leaving off the --tag=config

**Comment by kenske** [comment]
Sorry, I should have left that out of my initial comment. I'll edit it. That was one attempt to fix it, but I have tried it again without the tag and it still didn't work. I ended up just running the publish globally and it worked:

``php artisan vendor:publish``

**Comment by spekkionu** [comment]
Try wrapping the provider name in quotes.  It seems some terminals will remove the backslashes otherwise (it works for me in Windows but not on Linux).

`php artisan vendor:publish --provider="Spekkionu\ZendAcl\ZendAclServiceProvider"`

**Comment by kenske** [comment]
Thanks! That fixed it
